kind: ConfigMap
apiVersion: v1
metadata:
  name: thanos-ruler-custom-rules
data:
  custom_rules.yaml: |
    groups:
      - name: cluster-health
        rules:
        - alert: MemoryRequested-55
          annotations:
            summary: Notify when the total memory requested in the clusters is greater than 55%.
            description: "The cluster {{ $labels.cluster }} has more than 55% of the memory requested."
          expr: |
            <CHANGE ME>
          for: 5s
          labels:
            cluster: "{{ $labels.cluster }}"
            severity: warning
